name: CI Test

on: [push, pull_request]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: SRApid:test
        load: true

    - name: Create Test Input
      run: |
        echo "GSE76511" > test_gse.txt
        mkdir output

    - name: Run Pipeline (Test Mode)
      # We skip --sra_db and --geo_db to force online mode / skip GEO part
      # We use --test_limit 20 to use fastq-dump -X 20
      run: |
        docker run --rm \
          -v $(pwd):/data \
          name: Docker Publish

on:
  push:
    branches: [ "main", "master" ]
    # Publish tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'format("refs/heads/{0}", "main")' }}
            type=ref,event=tag

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}:test \
          --gse_list test_gse.txt \
          --out_dir ./output \
          --cpus 2 \
          --test_limit 20

    - name: Verify Outputs
      run: |
        echo "Checking outputs..."
        ls -R output/
        
        # Check if Validation CSV exists
        if [ -f "output/GSE_run_counts.csv" ]; then
            echo "Summary CSV found."
            cat output/GSE_run_counts.csv
        else
            echo "Summary CSV missing!"
            exit 1
        fi

        # Check if FASTQ folder exists (We assume GSE76511 has runs)
        # Note: In test mode we only download the first SRR found
        count=$(find output/fastq -name "*_R1.fastq.gz" | wc -l)
        if [ "$count" -gt 0 ]; then
            echo "Success: Downloaded $count FASTQ files."
        else
            echo "Error: No FASTQ files downloaded."
            exit 1
        fi